format_version: 2
pipelines:
  PUBLISH_gocd_agents:
    group: GoCD
    label_template: ${code[:10]}
    materials:
      code:
        type: configrepo
        destination: code
    stages:
    - publish_docker_image:
        jobs:
          gradle:
            elastic_profile_id: dind
            tasks:
              - script: 'cd code && docker build . -t stcarolas/gocd-agent-gradle:latest --build-arg AGENT_TYPE=gradle'
